#!/usr/bin/env python3
"""Regenerate CITATIONS.md from mechanisms.json.

The README has to say where the dates came from, and a hand-maintained citation table
drifts from the data the site actually renders. Generating it removes that possibility:
the table and the page are the same file, formatted twice.

Usage:  python tools/build_citations.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MECHANISMS = ROOT / "app" / "src" / "data" / "mechanisms.json"
OUT = ROOT / "CITATIONS.md"

KIND_LABEL = {
    "arxiv_v1": "arXiv v1",
    "release": "product release",
    "forum_post": "forum post",
}

HEADER = """# Citations and date evidence

Generated by `tools/build_citations.py` from `app/src/data/mechanisms.json`.
Do not edit by hand - regenerate instead.

Every row marked **arXiv v1** is checked automatically against the arXiv API by
`tools/verify_dates.py`, which compares both the submission date and the paper title and
exits non-zero on any mismatch. The title check exists so that a transposed identifier
cannot silently point at a different paper.

Rows not marked arXiv v1 have no preprint. They carry written evidence naming the dated
artifact the date comes from, and are listed separately at the end.

## Why the v1 date

A paper's arXiv `published` field is the date version 1 was submitted. That is used here
as the launch date because it is the first moment the work was public, it is
machine-checkable, and it is stable - later revisions change the content but not the v1
timestamp. Conference publication dates are often months later and would compress the
timeline misleadingly.

Note that the arXiv identifier prefix is **not** a reliable date. Identifiers are
assigned around the announcement cycle, so YaRN is `2309.00071` but was submitted 31
August 2023, and Titans is `2501.00663` but was submitted 31 December 2024.

"""


def main() -> int:
    mechanisms = json.loads(MECHANISMS.read_text(encoding="utf-8"))
    mechanisms.sort(key=lambda m: m["date"])

    papers = [m for m in mechanisms if m["date_kind"] == "arxiv_v1"]
    others = [m for m in mechanisms if m["date_kind"] != "arxiv_v1"]

    lines = [HEADER]
    lines.append(f"## Verified against the arXiv API ({len(papers)})\n")
    lines.append("| Date (v1) | Mechanism | arXiv | Title as arXiv records it |")
    lines.append("|---|---|---|---|")
    for m in papers:
        title = (m.get("title_check") or "").replace("|", "\\|")
        lines.append(
            f"| {m['date']} | {m['name']} | [{m['arxiv']}]({m['url']}) | {title} |"
        )

    lines.append(f"\n## Dated by a non-paper source ({len(others)})\n")
    lines.append(
        "These are exempt from the API check because no preprint exists. They are *not* "
        "waved through: `verify_dates.py` fails them unless they carry a written "
        "`date_evidence` string.\n"
    )
    for m in others:
        lines.append(f"### {m['name']} — {m['date']}")
        lines.append(f"\n- **Kind:** {KIND_LABEL[m['date_kind']]}")
        lines.append(f"- **Source:** <{m['url']}>")
        lines.append(f"- **Evidence:** {m.get('date_evidence', '')}\n")

    counts: dict[str, int] = {}
    for m in mechanisms:
        counts[m["category"]] = counts.get(m["category"], 0) + 1

    lines.append("## Coverage by category\n")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for cat, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {cat} | {n} |")

    # Deliberately no "generated on" timestamp. CI regenerates this file and fails
    # if it differs from what is committed, so a date that changes by itself would
    # break the build on the first day nobody touched the data. Git already records
    # when this file last changed, and it records it accurately.
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"{len(mechanisms)} mechanisms total.")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(mechanisms)} mechanisms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
