# -*- coding: utf-8 -*-
"""
build_plan.py - renders MIXTURE_PLAN.md and mixture_results.json from spec.py
via audit.py.

No number in the plan is hand-typed. Change spec.py, re-run this, and the
document re-derives. If an invariant breaks, nothing is written.
"""

import io
import json
import os
import sys

import spec
import audit
import polish

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_MD = os.path.join(HERE, "..", "MIXTURE_PLAN.md")
OUT_JSON = os.path.join(HERE, "..", "mixture_results.json")


# --- formatting -------------------------------------------------------------

def T(x):
    """Token counts at the magnitude a reader can hold in their head."""
    if x >= 1e12:
        return f"{x/1e12:.2f}T"
    if x >= 1e9:
        return f"{x/1e9:.1f}B"
    if x >= 1e6:
        return f"{x/1e6:.1f}M"
    return f"{x:,.0f}"


def pct(x, d=2):
    return f"{x:.{d}f}%"


def usd(x):
    return f"${x:,.0f}"


VERDICT_GLOSS = {
    "SUPPLY-OK": "fits inside one pass of real data",
    "REPEAT":    "reachable only by repeating data, within the 4-epoch ceiling",
    "GENERATE":  "cannot be reached from existing data at any tolerable epoch count",
}


def build():
    r = audit.run()
    r["sweep"] = audit.sweep()
    r["sensitivity"] = audit.sensitivity_analysis()
    _mp = os.path.join(HERE, "..", "microproxy_results.json")
    r["microproxy"] = (json.load(io.open(_mp, encoding="utf-8"))
                       if os.path.exists(_mp) else None)
    _dp = os.path.join(HERE, "..", "decon_results.json")
    r["decon"] = (json.load(io.open(_dp, encoding="utf-8"))
                  if os.path.exists(_dp) else None)
    L = []
    w = L.append

    lanes = r["lanes"]
    audited = r["audited"]
    by_id = {a["id"]: a for a in audited}
    phases = r["phases"]
    cost = r["cost"]
    g = spec.GATING

    # -- header --------------------------------------------------------------
    w("# Drishtikon-40B — V5 Mixture & Curriculum Specification")
    w("")
    g0 = spec.GATING
    def _badge(label, value, color):
        lab = label.replace(" ", "%20").replace("-", "--")
        val = str(value).replace(" ", "%20").replace("-", "--")
        return (f"![{label}: {value}]"
                f"(https://img.shields.io/badge/{lab}-{val}-{color}"
                f"?style=flat-square&labelColor=1E2230)")
    w(" ".join([
        _badge("budget", f"{T(r['budget'])} tokens", "3B4CC0"),
        _badge("data gate", f"{g0['measured_clean_tokens']/1e6:.1f}M cleaned", "0ca30c"),
        _badge("lanes", str(len(r["audited"])), "2a78d6"),
        _badge("invariants", "all passing", "0ca30c"),
        _badge("proxy screen", f"${r['cost']['total_usd']:,.0f}", "6C7385"),
    ]))
    w("")
    w(f"**Budget:** {T(r['budget'])} pretraining tokens · "
      f"{T(spec.MODEL_PARAMS)} dense parameters · "
      f"~{r['budget']/spec.MODEL_PARAMS:.0f} tokens/param. The budget is a "
      f"**parameter**, not an assumption — §3.1 audits the same mixture across "
      f"2.4T / 3T / 4T / 14T and reports which survive. "
      f"{T(r['budget'])} is the midpoint of the range session 5 named.")
    w("")
    w("[[TIP]] **Read this as a rendered page** → "
      "[rahulni.github.io/Indic_LLM/5_data_mixture_curriculum/site.html]"
      "(https://rahulni.github.io/Indic_LLM/5_data_mixture_curriculum/site.html) "
      "— sticky contents, full-text search, cross-links and figures drawn from "
      "the same audit data. GitHub shows `.html` files as source, never rendered, "
      "so the file itself ([`site.html`](site.html), built by "
      "[`plan/build_site.py`](plan/build_site.py)) needs a host: GitHub Pages "
      "above, or open it locally, or "
      "[raw.githack.com](https://raw.githack.com/rahulni/Indic_LLM/main/5_data_mixture_curriculum/site.html) "
      "without any setup.")
    w("")
    w("Every number below is generated by [`plan/spec.py`](plan/spec.py) → "
      "[`plan/audit.py`](plan/audit.py) → [`plan/build_plan.py`](plan/build_plan.py). "
      "Nothing is hand-typed. The build refuses to emit this document if any "
      "invariant fails — phase weights that do not sum to 1, lane shares that do "
      "not sum to 100, a floor above its own lane's share, an Indic tier split "
      "that does not close, or a lane that needs manufactured tokens without a "
      "costed manufacturing plan.")
    w("")

    # -- thesis --------------------------------------------------------------
    web = by_id["web"]
    code = by_id["code"]
    ag = by_id["agentic"]
    ind = by_id["indic"]
    w("## 1. The claim")
    w("")
    w("Three findings drive every number in this plan, and all three are "
      "arithmetic rather than preference.")
    w("")
    sweep = r["sweep"]
    failed = [s for s in sweep if not s["feasible"]]
    w(f"**One: the online selector doubles every supply requirement, and that is "
      f"what settles the budget question.** With a "
      f"{spec.SELECTOR['keep_fraction']*100:.0f}% keep-fraction, discarded "
      f"batches are thrown away and never re-offered, so the corpus must supply "
      f"**candidate** tokens, not trained tokens. Lanes protected by the "
      f"always-on floor bypass selection and are consumed 1:1; everything else "
      f"is drawn at 2×. Applied honestly (§5.2), this is decisive: the mixture "
      f"is comfortable across the 2.4–4T range the session named, and "
      f"**infeasible at the 14T of session 3's design memo — where the *web* "
      f"lane itself runs dry** (§3.1). Not the agentic lane, not Indic. The most "
      f"abundant data on earth.")
    w("")
    w(f"**Two: the specialist lanes still cannot be filled by finding data.** "
      f"Even at {T(r['budget'])}, giving the agentic lane {pct(ag['share'])} "
      f"would take **{ag['epochs']:.0f} epochs** of every agentic trajectory "
      f"ever published — Nemotron-SWE, SWE-smith, SWE-Gym, ToolBench, "
      f"AgentInstruct, xLAM and Glaive together are {T(ag['supply_usable'])} of "
      f"usable tokens against {T(ag['demand'])} of candidate demand. The lane is "
      f"{pct(ag['manufactured_pct'],1)} manufactured and §6 prices it. Any plan "
      f"assigning agentic a double-digit share without a rollout harness behind "
      f"it is describing data that does not exist.")
    w("")
    tr = next(t for t in r["indic_tiers"] if t["tier"] == "translated")
    ver = next(t for t in r["indic_tiers"] if t["tier"] == "verified")
    w(f"**Three: at this budget the Indic lane runs on verified text alone.** "
      f"This reverses the previous draft. Sizing Indic at {pct(ind['share'])} of "
      f"{T(r['budget'])} means {T(ind['demand'])} of candidate demand, which "
      f"Sangraha Verified covers at **{pct(ver['share_of_lane'],1)} of the "
      f"lane** — leaving the entire {T(tr['available'])} machine-translated tier "
      f"**unused** and requiring **zero synthetic Indic**. Session 3's 20% share "
      f"remains withdrawn, but the reason has changed: not that Indic data is "
      f"unobtainable, but that at a defensible budget we can afford to be "
      f"choosy about which tier we take (§7).")
    w("")
    if r["at_ceiling"]:
        for c in r["at_ceiling"]:
            w(f"[[WARNING]] **At the ceiling:** the {c['label'].lower()} lane sits at "
              f"**{c['epochs']:.2f} of its {c['cap']:.1f}-epoch cap** — under 2% "
              f"headroom. One revision to the dedup haircut or the fertility "
              f"conversion pushes it into `GENERATE`. It is reported as `REPEAT` "
              f"but should not be read as comfortable.")
        w("")
    w(f"The plan is a hypothesis. §13 specifies {len(spec.PROXY['arms'])} arms at "
      f"1B and a 3B confirmation, with pre-registered decision rules, for "
      f"{usd(cost['total_usd'])} — **{cost['pct_of_full']:.3f}% of the "
      f"{usd(cost['full_run']['usd'])} full run**. That screen has **not** been "
      f"run; it needs GPUs we do not have.")
    w("")
    _mp = r.get("microproxy")
    if _mp:
        _cc = _mp.get("claim_crossfade", {})
        _cf = _mp.get("claim_floor", {})
        w(f"What *has* been run is a much narrower experiment on the hardware "
          f"available — an 11M-parameter byte-level model on the two corpora we "
          f"actually hold, testing only the two claims here that are training-"
          f"dynamics claims rather than capability claims (§13.7). It returns "
          f"verdicts on both: **{_cc.get('verdict','—')}** and "
          f"**{_cf.get('verdict','—')}**. Two other measurements in this "
          f"document are also real rather than asserted: the data gate (§2) and "
          f"benchmark contamination (§13.5). Everything else is arithmetic over "
          f"published supply figures, and is labelled as such.")
        w("")

    # -- gate ----------------------------------------------------------------
    w("## 2. Data-gating status")
    w("")
    w(f"**{g['measured_clean_tokens']:,} cleaned tokens** across "
      f"{g['measured_clean_docs']:,} documents, from {g['measured_raw_tokens']:,} "
      f"raw. Each corpus is deterministic across two runs in separate "
      f"interpreters with different `PYTHONHASHSEED`. Source: `{g['source']}`.")
    w("")
    w(f"Session 4 stood at {g['session4_clean_tokens']:,}. This session added "
      f"**{g['added_this_session']:,}** by cleaning the tier §16 ranks first — "
      f"a **{g['growth_multiple']:.2f}×** cumulative gate, and the added tokens "
      f"are the only ones in this table the anneal will accept.")
    w("")
    w("| Corpus | Session | Lane | Tier | Raw tokens | Raw docs | Docs surviving | Note |")
    w("|---|---|---|---|---|---|---|---|")
    for c in g["corpora"]:
        w(f"| {c['name']} | {c.get('session','4')} | `{c['lane']}` | "
          f"{c['tier'] or '—'} | {c['raw_tokens']:,} | {c['raw_docs']:,} | "
          f"{c['final_docs']:,} | {c['note']} |")
    w("")
    unv = next(t for t in r["indic_tiers"] if t["tier"] == "unverified")
    w(f"**The audit redirected this effort, and the redirection has been "
      f"carried out.** Session 4 cleaned Sangraha *unverified*. At "
      f"{T(r['budget'])} that tier supplies only "
      f"{pct(unv['share_of_lane'],1)} of the Indic lane, leaves "
      f"{T(unv['unused'])} of itself unused, and is barred from the anneal "
      f"outright — while Sangraha *Verified* carries "
      f"{pct(ver['share_of_lane'],1)} of the lane and is the only tier the "
      f"cooldown will accept. So the priority-1 job in §16 was run rather than "
      f"just written down, and the row above is its output. What it turned up "
      f"along the way — a length bias in the quality filter that silently "
      f"discards ~10% of that tier — is in §16.1.")
    w("")
    w(f"The reasoning corpus remains in a lane that is "
      f"{by_id['reasoning']['manufactured_pct']:.0f}% manufactured with three of "
      f"its four sources failing the licence gate; that is priority 2 and has "
      f"not been done.")
    w("")

    # -- phases --------------------------------------------------------------
    w("## 3. Budget and phase schedule")
    w("")
    w("| Phase | Share | Tokens | Purpose |")
    w("|---|---|---|---|")
    for p in phases:
        w(f"| **{p['id']} · {p['label']}** | {pct(p['weight']*100,0)} | "
          f"{T(p['tokens'])} | {p['why']} |")
    w("")
    # Curriculum shape as a diagram: GitHub renders mermaid natively, and the
    # phase progression is the one thing in this document that is genuinely a
    # shape rather than a number.
    w("```mermaid")
    w("%%{init: {'theme':'base','themeVariables':{"
      "'primaryColor':'#1E2230','primaryTextColor':'#E8EAF0',"
      "'primaryBorderColor':'#39404F','lineColor':'#7C8496',"
      "'fontFamily':'ui-monospace, monospace','fontSize':'13px'}}}%%")
    w("flowchart LR")
    for i, p in enumerate(phases):
        top = sorted(spec.LANES.items(),
                     key=lambda kv: -kv[1]["phases"][p["idx"]])[:2]
        desc = "<br/>".join(f"{spec.LANES[k]['label']} {v['phases'][p['idx']]:.0f}%"
                            for k, v in top)
        w(f'  P{i}["<b>{p["id"]} · {p["label"]}</b><br/>{pct(p["weight"]*100,0)} '
          f'· {T(p["tokens"])}<br/><br/>{desc}"]')
    w("  " + " --> ".join(f"P{i}" for i in range(len(phases))))
    w("  " + " ".join(f"style P{i} fill:#1E2230,stroke:#39404F,color:#E8EAF0"
                      for i in range(len(phases))))
    w("```")
    w("")
    w("Scarce lanes are held small early and concentrated late: agentic runs "
      f"{spec.LANES['agentic']['phases'][0]:.1f}% of Phase A and "
      f"{spec.LANES['agentic']['phases'][-1]:.0f}% of the anneal. The model "
      "cannot use premium data before it can use it, so premium data is not "
      "spent on it.")
    w("")
    w("### 3.1 Budget sweep")
    w("")
    w("Session 3's design memo locked 14T for a 40B dense model. Session 5, "
      "asked the question directly, answered *\"between 2.4 to 4 trillion "
      "tokens\"* for what V5 actually trains on. Those are different numbers for "
      "different things, so the budget is a **parameter** and the same mixture "
      "is audited across the whole range. A scenario that fails is not a broken "
      "build — it is the finding.")
    w("")
    w("| Budget | Feasible | `GENERATE` lanes | At epoch ceiling | Manufacturing | Run cost | Run time | Worst lane |")
    w("|---|---|---|---|---|---|---|---|")
    for s in sweep:
        star = " ⭐" if abs(s["budget"] - r["budget"]) < 1 else ""
        if s["feasible"]:
            w(f"| **{T(s['budget'])}**{star} | ✅ | {s['generate_lanes']} | "
              f"{s['at_ceiling']} | {usd(s['manufacturing_usd'])} | "
              f"{usd(s['full_run_usd'])} | {s['full_run_days']:.1f} d | "
              f"{s['worst_lane']} @ {s['worst_pct']:.0f}% |")
        else:
            w(f"| **{T(s['budget'])}**{star} | ❌ | — | — | — | — | — | "
              f"*build refused* |")
    w("")
    for s in sweep:
        w(f"- **{T(s['budget'])}** — {s['note']}")
    w("")
    if failed:
        f0 = failed[0]
        w(f"[[CAUTION]] **Why {T(f0['budget'])} fails.** The build refuses it, and the "
          f"invariant that fires is not the one anyone would predict:")
        w("")
        w(f"> `{f0['error']}`")
        w("")
        w("Not agentic. Not Indic. **Web.** At 14T the web lane needs more "
          "high-quality English tokens than exist, once its counts are converted "
          "to our tokenizer (§5.1) and doubled for the selector's discard rate "
          "(§5.2). There is no manufacturing plan for general web because "
          "manufacturing general web is not a coherent thing to do — synthetic "
          "web is just the model's own prior fed back to it. The 14T figure was "
          "sound for a corpus-unconstrained thought experiment and does not "
          "survive contact with the actual inventory.")
        w("")
    w(f"Everything below is computed at **{T(r['budget'])}**, the midpoint of "
      f"the range the session named. Re-run any scenario with "
      f"`python -c \"import audit,json; print(audit.run(4e12)['audited'])\"`.")
    w("")

    # -- mixture -------------------------------------------------------------
    w("## 4. The mixture")
    w("")
    w("Per-phase shares are the specification. **The whole-run share is derived "
      "as their token-weighted average — it is an output of the curriculum, not "
      "an independent input.** This is deliberate: it makes it impossible to "
      "declare a whole-run number the phase schedule does not actually deliver.")
    w("")
    hdr = " | ".join(f"{p['id']}" for p in phases)
    w(f"| Lane | {hdr} | **Whole-run** | Tokens | Loss-bearing | Benchmarks it must win |")
    w("|---|" + "---|" * len(phases) + "---|---|---|---|")
    for lane in lanes:
        cols = " | ".join(f"{v:.1f}" for v in lane["phases"])
        w(f"| {lane['label']} | {cols} | **{pct(lane['share'])}** | "
          f"{T(lane['tokens'])} | {T(lane['loss_bearing_tokens'])} "
          f"({lane['loss_bearing_frac']*100:.0f}%) | "
          f"{'; '.join(lane['benchmarks'][:3])} |")
    w(f"| **Total** | " + " | ".join("100.0" for _ in phases) +
      f" | **100.00%** | {T(spec.BUDGET_TOKENS)} | | |")
    w("")
    w("**On the loss-bearing column.** The budget is denominated in raw tokens "
      "because we pay compute for every token in the context window. But the "
      f"agentic lane carries loss on only {spec.LOSS_BEARING['agentic']*100:.0f}% "
      f"of its tokens — the issue body, the user turn, the 4,000-line stack trace "
      f"a tool returns are all read and none are trained on (§12). "
      f"{pct(ag['share'])} of budget buys {T(ag['loss_bearing_tokens'])} of "
      "actual supervision. Reporting only the raw share would overstate this "
      "lane by more than 3×.")
    w("")

    # -- supply audit --------------------------------------------------------
    w("## 5. Supply audit")
    w("")
    w("### 5.1 Everything is converted to one tokenizer first")
    w("")
    w("An earlier draft of this document added FineWeb-Edu's GPT-2 tokens to "
      "DCLM's GPT-NeoX tokens to The Stack v2's StarCoder2 tokens to Sangraha's "
      "Indic-sentencepiece tokens, and then claimed a separate 1.33× credit for "
      "our Indic-efficient tokenizer on top. That is two errors compounding: the "
      "sum was not in any single unit, and the efficiency gain was counted "
      "twice. An epoch count is only meaningful when supply and demand share "
      "units, and the 14T budget is denominated in **our** tokens.")
    w("")
    w("Words are the invariant. Each published count is divided by its own "
      "tokenizer's fertility to recover words, then multiplied by ours exactly "
      "once. The two measured rows come from our own session-4 pipeline.")
    w("")
    used = {audit.resolve_units(it) for it in spec.INVENTORY}
    w("| Tokenizer | Content | Tokens/word | Used | Provenance |")
    w("|---|---|---|---|---|")
    for tok in ("ours", "cl100k", "muril", "gpt2", "neox", "starcoder2", "indic_sp"):
        for cls, val in spec.TOKENIZER_FERTILITY[tok].items():
            prov = spec.FERTILITY_PROVENANCE.get((tok, cls))
            if prov is None:
                prov = ("ESTIMATED — standard fertility for this tokenizer class"
                        if (tok, cls) in used else "ESTIMATED — reference only, not used")
            mark = "✅" if (tok, cls) in used else "—"
            bold = "**" if tok == "ours" else ""
            w(f"| {bold}`{tok}`{bold} | {cls} | {bold}{val:.3f}{bold} | {mark} | {prov} |")
    w("")
    w("The `cl100k` and `muril` rows are the empirical spine of this table: they "
      "are the same Telugu corpus measured twice by our own pipeline, and the "
      "5.78× gap between them is why a token count means nothing without its "
      "tokenizer.")
    w("")
    w("| Lane | Published (source units) | In our units | Factor |")
    w("|---|---|---|---|")
    for a in audited:
        src_total = sum(s["tokens_src"] for s in a["sources"])
        our_total = sum(s["tokens_ours"] for s in a["sources"])
        if not src_total:
            continue
        w(f"| {a['label']} | {T(src_total)} | {T(our_total)} | "
          f"×{our_total/src_total:.3f} |")
    w("")
    w("**This changed verdicts, not just decimals.** Every factor in the right "
      "column is below 1.0 for the lanes whose counts came from coarser "
      "tokenizers, so the conversion *shrinks* real supply across the board — "
      "Indic hardest, at "
      f"×{sum(s['tokens_ours'] for s in by_id['indic']['sources'])/sum(s['tokens_src'] for s in by_id['indic']['sources']):.3f}. "
      "When this plan was still written against a 14T budget the conversion "
      "moved web from `SUPPLY-OK` to `REPEAT` and pushed code onto its epoch "
      "cap. It is the direction an accounting fix should move a plan that was "
      "previously double-counting in its own favour, and it is a large part of "
      "why 14T does not survive §3.1.")
    w("")
    w("[[IMPORTANT]] **The load-bearing assumption.** Sangraha publishes a token count without "
      "naming its tokenizer. We assume an Indic sentencepiece at "
      f"{spec.TOKENIZER_FERTILITY['indic_sp']['indic']:.2f} tok/word. If those "
      f"251.3B tokens were instead counted with a cl100k-class tokenizer — which "
      f"our own measurement puts at "
      f"{spec.TOKENIZER_FERTILITY['cl100k']['indic']:.3f} tok/word on Telugu, "
      f"{spec.TOKENIZER_FERTILITY['cl100k']['indic']/spec.TOKENIZER_FERTILITY['muril']['indic']:.2f}× "
      f"worse than MuRIL — the real Indic supply would be roughly "
      f"{spec.TOKENIZER_FERTILITY['indic_sp']['indic']/spec.TOKENIZER_FERTILITY['cl100k']['indic']:.2f}× "
      "what is assumed here and the Indic lane would be almost entirely "
      "manufactured. Confirming Sangraha's tokenizer is the single cheapest "
      "risk-reduction available to this plan.")
    w("")
    w("### 5.2 The selector doubles the requirement")
    w("")
    s = spec.SELECTOR
    w(f"An earlier draft used `keep_fraction` only in prose. It belongs in the "
      f"arithmetic. The selector retains "
      f"{s['keep_fraction']*100:.0f}% of {s['candidate_batch']:,} candidates per "
      f"refresh and **discards the rest permanently** — session 5 is explicit "
      f"that a rejected batch is thrown away rather than re-offered, and that "
      f"\"if you collect one token actually only half will be trained on\". So "
      f"the corpus must cover *candidate* tokens.")
    w("")
    w("The multiplier is per-lane, not global. Data admitted under the protected "
      "floor bypasses the selector and is consumed 1:1; everything above the "
      "floor is drawn at 1/keep_fraction. A lane that is mostly floor barely "
      "notices — which is a second, previously unstated benefit of the floor.")
    w("")
    w("| Lane | Whole-run share | Floor (bypasses selector) | Multiplier | Trained tokens | **Candidate tokens** |")
    w("|---|---|---|---|---|---|")
    for a in audited:
        fl = spec.FLOOR.get(a["id"], {}).get("pct", 0.0)
        w(f"| {a['label']} | {pct(a['share'])} | {pct(fl,2)} | "
          f"×{a['selector_mult']:.3f} | {T(a['trained'])} | **{T(a['demand'])}** |")
    tot_tr = sum(a["trained"] for a in audited)
    tot_cd = sum(a["demand"] for a in audited)
    w(f"| **Total** | 100.00% | {pct(r['floor_total'],2)} | "
      f"**×{tot_cd/tot_tr:.3f}** | {T(tot_tr)} | **{T(tot_cd)}** |")
    w("")
    w(f"The plan trains {T(tot_tr)} and must therefore hold {T(tot_cd)} of "
      f"cleaned, licensed, deduplicated corpus. Every epoch count in §5.3 is "
      f"against the candidate column. Auditing against the trained column — "
      f"which the previous draft did — understated every lane by up to 2×.")
    w("")
    w(f"Against this cost, the selector's claimed benefit is "
      f"{s['claimed_efficiency']}. If that holds even partially it is worth "
      f"paying 2× corpus for; if it does not, the honest move is to drop the "
      f"selector and train on everything. That is not tested by the proxy in "
      f"§13 and should be.")
    w("")
    w("### 5.3 Supply against demand")
    w("")
    w("Usable supply = converted tokens × cross-corpus dedup survival. Capped "
      "supply = usable × the per-source epoch cap. The 4.0-epoch default ceiling "
      "is from Muennighoff et al., *Scaling Data-Constrained Language Models* "
      "(NeurIPS 2023): repetition up to ~4 epochs is near-equivalent to fresh "
      "data, and decays sharply after.")
    w("")
    w("| Lane | Demand | Usable supply | Epochs needed | Filled from real data<br>(incl. repeats) | Manufactured | Verdict |")
    w("|---|---|---|---|---|---|---|")
    for a in audited:
        ep = "∞" if a["epochs"] == float("inf") else f"{a['epochs']:.2f}"
        w(f"| {a['label']} | {T(a['demand'])} | {T(a['supply_usable'])} | "
          f"**{ep}** | {T(a['found'])} | {T(a['manufactured'])} "
          f"({a['manufactured_pct']:.1f}%) | `{a['verdict']}` |")
    w("")
    for k, v in VERDICT_GLOSS.items():
        w(f"- `{k}` — {v}")
    w("")
    w("### 5.4 Repetition is not free below the cap")
    w("")
    d = spec.EPOCH_DECAY
    w(f"An earlier draft treated everything under 4 epochs as equivalent to "
      f"fresh data. That is the paper's headline, not its result. "
      f"{d['citation']} fits a smooth decay:")
    w("")
    w("```")
    w("D' = U + U · R* · (1 − exp(−R / R*)),    R = epochs − 1,    R* = "
      f"{d['r_star_data']}")
    w("```")
    w("")
    w(f"At the 4.0 cap this yields **{audit.effective_multiplier(4.0):.3f} "
      f"effective epochs, not 4.0** — the fourth pass is worth about a quarter "
      f"of a fresh one. Physical feasibility is unchanged; what changes is the "
      f"value delivered, so it is reported as its own column rather than "
      f"folded into the verdict.")
    w("")
    w("| Lane | Epochs run on real data | Effective yield | Tokens found | Effective tokens | Value lost to repetition |")
    w("|---|---|---|---|---|---|")
    tot_loss = 0.0
    for a in audited:
        cap = a["supply_capped"] / a["supply_usable"] if a["supply_usable"] else 0.0
        run_ep = min(a["epochs"], cap)
        tot_loss += a["repetition_loss"]
        w(f"| {a['label']} | {run_ep:.2f} | "
          f"×{audit.effective_multiplier(run_ep):.2f} | {T(a['found'])} | "
          f"{T(a['effective_tokens'])} | {T(a['repetition_loss'])} |")
    w(f"| **Total** | | | | | **{T(tot_loss)}** |")
    w("")
    w(f"{T(tot_loss)} of nominal budget buys nothing. That is "
      f"{100*tot_loss/r['budget']:.2f}% of the run — small enough not to change "
      f"a lane decision, large enough that claiming otherwise would be a free "
      f"lie. Manufactured tokens carry no discount because they are fresh by "
      f"construction.")
    w("")
    w(f"*Caveat, since this number is now load-bearing:* {d['confidence']}")
    w("")
    w("Two entries deserve the reviewer's pressure before anything else:")
    w("")
    w(f"- **Code at {pct(code['share'])} is not a preference, it is a ceiling.** "
      f"{code['epochs']:.2f} epochs of The Stack v2 sits just under the 4.0 cap. "
      f"We would take more code; the corpus does not exist. Arm A3 (§13) "
      f"deliberately violates this ceiling so the constraint is falsifiable "
      f"rather than assumed.")
    w(f"- **Reasoning is {by_id['reasoning']['manufactured_pct']:.0f}% "
      f"manufactured.** Stated plainly rather than buried: arXiv, FineMath, "
      f"OpenWebMath, AlgebraicStack, OpenThoughts2 and OpenR1 together supply "
      f"{T(by_id['reasoning']['supply_usable'])} usable, and four epochs of that "
      f"is {T(by_id['reasoning']['supply_capped'])} against "
      f"{T(by_id['reasoning']['demand'])} of demand. Synthesis is the established "
      f"state of the art here (phi-4, Cosmopedia), it is cheap, and §6 prices it "
      f"— but the reviewer should know it is 70% of the lane.")
    w("")

    # -- manufacturing -------------------------------------------------------
    w("## 6. Manufacturing plan")
    w("")
    w("Every shortfall from §5 is costed. `GENERATE` means the tokens do not "
      "exist and must be produced by inference (and, for agentic, by executing a "
      "real environment). `COLLECT` means they exist in the world but sit in no "
      "corpus — the cost is crawling, OCR and licensing, not GPU time.")
    w("")
    w("| Lane | Need | Units | Kind | GPU-h | Cost | Wall-clock | Method |")
    w("|---|---|---|---|---|---|---|---|")
    for m in r["manufacturing"]:
        w(f"| {m['label']} | {T(m['need'])} ({m['need_pct']:.0f}%) | "
          f"{m['units']:,.0f} | `{m['kind']}` | {m['gpu_hours']:,.0f} | "
          f"{usd(m['usd'])} | {m['wall_days']:.2f} d | {m['method']} |")
    w(f"| **Total** | | | | | **{usd(r['manufacturing_usd'])}** | | "
      f"{100*r['manufacturing_usd']/cost['full_run']['usd']:.1f}% of the full-run cost |")
    w("")
    w("Risks and fallbacks, because a manufacturing plan with no failure branch "
      "is the same wishful accounting in a different costume:")
    w("")
    for m in r["manufacturing"]:
        w(f"- **{m['label']}** — *Risk:* {m['risk']} *Fallback:* {m['fallback']}")
    w("")
    ag_m = next(m for m in r["manufacturing"] if m["id"] == "agentic")
    w(f"The agentic number is the one to interrogate: **{ag_m['units']:,.0f} "
      f"verifier-green trajectories**. At 60 s of environment time each across "
      f"10,000 parallel containers that is {ag_m['env_days']:.2f} days of "
      f"wall-clock and {usd(ag_m['usd'])} of inference. The cost is not the "
      f"obstacle — the harness is. Session 5 was explicit that V4 never built "
      f"one, and without a live terminal there is no agentic lane at any price.")
    w("")

    # -- indic ---------------------------------------------------------------
    w("## 7. The Indic slot, split four ways")
    w("")
    w(f"Lane total **{T(r['indic_demand'])}** ({pct(ind['share'])} of budget). "
      f"Tier sizes are the same supply arithmetic as every other lane: each real "
      f"tier is its published token count at its own epoch cap, and the synthetic "
      f"tier is the **residual** — what is left once real supply is exhausted. "
      f"That is the only honest way to size a tier that does not yet exist.")
    w("")
    w("| Tier | Share of lane | Tokens used | Available at cap | **Unused** | Source | Published | Epoch cap | Anneal-eligible |")
    w("|---|---|---|---|---|---|---|---|---|")
    for t in r["indic_tiers"]:
        head = (f"**{t['tier']}** | {pct(t['share_of_lane'],1)} | "
                f"{T(t['tokens'])} | {T(t['available'])} | "
                f"**{T(t['unused'])}**")
        if t["sources"]:
            for i, s in enumerate(t["sources"]):
                cell = head if i == 0 else " | | | | "
                w(f"| {cell} | {s['name']} | {T(s['tokens'])} | "
                  f"{s['epoch_cap']}× | "
                  f"{'yes' if t['tier']=='verified' else 'no'} |")
        else:
            w(f"| {head} | *manufactured — does not exist yet* | — | — | no |")
    w("")
    declined = [t for t in r["indic_tiers"] if t["unused"] > 0]
    if declined:
        tot = sum(t["unused"] for t in declined)
        names = ", ".join(f"{t['tier']} ({T(t['unused'])})" for t in declined)
        w(f"**The `Unused` column is the argument.** {T(tot)} of real, "
          f"downloadable Indic tokens are **available and deliberately "
          f"declined** — {names}. This is not a supply failure; it is a quality "
          f"choice the budget can afford. A reviewer should push on it in the "
          f"opposite direction to the usual one: not *why is this lane so "
          f"small*, but *why leave that much real data on the floor*. The answer "
          f"is the epoch-cap and tier-priority ordering in §5.3 — verified text "
          f"at 4 epochs is preferred to machine-translated Wikipedia at 1.5, and "
          f"at 3T we never have to make that trade.")
        w("")
    w("**The correction a reviewer should check first.** AI4Bharat labels its "
      "162.7B-token component *Synthetic*. It is not. It is WikiMedia English "
      "machine-translated into 14 languages and then transliterated — that is the "
      "**translated** tier. Taking the label at face value would let this plan "
      "claim a large synthetic tier it never built, while hiding the "
      "translationese risk that actually applies. The tiers here are named for "
      "what the data is, not what the card calls it. The epoch cap follows: 1.5× "
      "on translated, because translationese compounds under repetition, against "
      "4.0× on verified.")
    w("")
    w("Tier rules: the verified tier is the only one admitted to the anneal; "
      "unverified may never substitute for the verified half of the protected "
      "floor; synthetic Indic is generated **from verified seeds only**, never "
      "from the translated tier, to avoid amplifying translationese through a "
      "feedback loop.")
    w("")
    w(f"**Why {pct(ind['share'])} is enough — and the credit this plan no longer "
      f"claims.** An earlier draft argued that our Indic-efficient tokenizer "
      f"made this share worth ~1.33× its face value. That credit is now spent "
      f"inside the unit conversion in §5.1, where every Indic token is already "
      f"restated in our tokenizer, so claiming it again here would be counting "
      f"it twice. It is withdrawn. What defends the share is narrower and "
      f"checkable: (i) the {spec.FLOOR['indic']['pct']}% protected floor "
      f"guarantees presence in *every* window, which matters more for retention "
      f"than bulk share; (ii) Indic rises to "
      f"{spec.LANES['indic']['phases'][-1]:.0f}% of the anneal, verified-only, "
      f"where retention is actually decided. Arm A2 tests the first claim and "
      f"the plan commits in advance to dropping the floor if it fails.")
    w("")

    # -- named lanes ---------------------------------------------------------
    w("## 8. Agentic, reasoning, long-context — named against the inventory")
    w("")
    for lid in ("agentic", "reasoning", "longctx"):
        a = by_id[lid]
        w(f"### {a['label']} — {pct(a['share'])} ({T(a['demand'])})")
        w("")
        w(f"Benchmarks: {', '.join(a['benchmarks'])}.")
        w("")
        w("| Dataset | Samples | Tokens | Provenance | Dedup keep | Epoch cap |")
        w("|---|---|---|---|---|---|")
        for s in sorted(a["sources"], key=lambda x: -x["tokens"]):
            smp = f"{s['samples']:,.0f}" if s["samples"] else "—"
            w(f"| [{s['name']}]({s['url']}) | {smp} | {T(s['tokens'])} | "
              f"`{s['provenance']}` | {s['dedup_keep']:.2f} | {s['epoch_cap']}× |")
        w(f"| **Usable total** | | **{T(a['supply_usable'])}** | | | "
          f"**{T(a['supply_capped'])} at cap** |")
        w("")
        for s in sorted(a["sources"], key=lambda x: -x["tokens"]):
            if s["note"]:
                w(f"- *{s['name']}* — {s['note']}")
        w("")
        if lid == "longctx":
            w("**Long-context is charged once, not twice.** The repo-level packs "
              "are re-concatenated Stack v2 files. Those tokens are billed to "
              "this lane and removed from the code lane's demand — they are not "
              "counted in both. Separately, a sequence-length schedule runs "
              "across *all* lanes (8k in Phase A → 32k in B → 128k in C → 128k "
              "in D); that schedule is a packing decision and consumes no "
              "additional budget. Only genuinely long-native documents hold "
              "share here.")
            w("")

    # -- floor ---------------------------------------------------------------
    w("## 9. Protected always-on floor")
    w("")
    s = spec.SELECTOR
    w(f"**{pct(r['floor_total'],1)} of every {s['refresh_every_steps']}-step "
      f"window is reserved before the online selector runs.** The selector "
      f"(OPUS-style: a frozen ghost copy scores candidate samples by how much "
      f"their gradient aligns with a benchmark-gradient proxy, keeping the top "
      f"{s['keep_fraction']*100:.0f}% of {s['candidate_batch']:,} candidates) "
      f"operates only on the remaining {pct(100-r['floor_total'],1)}. The "
      f"corpus cost of that discard rate is priced in §5.2.")
    w("")
    w("| Lane | Floor | Whole-run share | Headroom | Restriction |")
    w("|---|---|---|---|---|")
    for f in r["floors"]:
        w(f"| {f['label']} | **{pct(f['floor'],2)}** | {pct(f['whole_run'])} | "
          f"{pct(f['headroom'])} | {f['note']} |")
    w(f"| **Total protected** | **{pct(r['floor_total'],2)}** | | | |")
    w("")
    w(f"**The floor exists because of a specific, known selector pathology, not "
      f"as a preference.** The selector scores a sample on its first "
      f"{s['scored_prefix_tokens']} tokens. An agentic trajectory opens with a "
      f"masked issue body and a tool log — text that looks like noise and scores "
      f"near zero. An Indic document is scored against a benchmark proxy that is "
      f"overwhelmingly English, so it registers as irrelevant however good it is. "
      f"Both lanes would be discarded for reasons unrelated to their value. Every "
      f"floor is strictly below its lane's whole-run share (the build asserts "
      f"this), so the floor constrains the selector without dictating the "
      f"mixture.")
    w("")
    w("The floor is also the plan's most attackable number, which is why arm A2 "
      "(§13) removes it entirely and the decision rule commits in advance to "
      "dropping it if the Indic metrics do not move.")
    w("")

    # -- anneal --------------------------------------------------------------
    w("## 10. The anneal reserve and schedule mechanics")
    an = r["anneal"]
    w("")
    w(f"**{T(an['tokens'])} — {pct(an['pct_of_budget'],1)} of the budget — held "
      f"back for the cooldown.** The reserve is not a separate set of numbers: "
      f"it *is* Phase D of the mixture table, which is what stops it from "
      f"drifting out of sync with the rest of the plan.")
    w("")
    w("| Lane | Share of reserve | Tokens | Share of that lane's lifetime budget |")
    w("|---|---|---|---|")
    for row in an["rows"]:
        w(f"| {row['label']} | {pct(row['share'],1)} | {T(row['tokens'])} | "
          f"{pct(row['pct_of_lane_lifetime'],1)} |")
    w("")
    w(f"**This reconciles the plan with the session-5 reference widget.** That "
      f"widget put agentic near 16% in the late mixture; this plan gives agentic "
      f"{pct(ag['share'])} of the whole run. Both are true. Agentic reaches "
      f"**{spec.LANES['agentic']['phases'][-1]:.0f}% of the anneal** — "
      f"{T(an['rows'][0]['tokens']) if an['rows'][0]['id']=='agentic' else ''}"
      f"{'' if an['rows'][0]['id']=='agentic' else T([x for x in an['rows'] if x['id']=='agentic'][0]['tokens'])}, "
      f"which is "
      f"{pct([x for x in an['rows'] if x['id']=='agentic'][0]['pct_of_lane_lifetime'],0)} "
      f"of everything agentic we will ever have — while staying small globally "
      f"because the supply does not exist to make it large globally. Scarce lanes "
      f"are made to count by *concentration*, not by share.")
    w("")
    w("Eligibility — what may enter the reserve:")
    w("")
    for e in spec.ANNEAL_ELIGIBILITY:
        w(f"- {e}")
    w("")
    w("### 10.1 Can the reserve actually be stocked?")
    w("")
    asup = r["anneal_supply"]
    w("Declaring eligibility rules is not the same as checking that enough data "
      "passes them. An earlier draft did the former and not the latter — the "
      "reserve was the one place in the plan where the quality bar was highest "
      "and the supply audit was missing entirely. It is now a build-breaking "
      f"invariant, and the reserve is held to **{spec.ANNEAL_MAX_EPOCHS:.0f} "
      f"epoch**: repeating data during a cooldown defeats the purpose of a "
      f"cooldown.")
    w("")
    w("| Lane | Reserve demand | Eligible pool | Yield | Eligible supply | Verdict | What the filter is |")
    w("|---|---|---|---|---|---|---|")
    for x in asup["rows"]:
        w(f"| {x['label']} | {T(x['demand'])} | {T(x['pool'])} | "
          f"{x['yield_frac']:.2f} | {T(x['eligible'])} | "
          f"{'✅' if x['ok'] else '❌ short ' + T(x['shortfall'])} | {x['basis']} |")
    w("")
    tight = [x for x in asup["rows"] if x["eligible"] < x["demand"] * 1.15]
    w("**This check failed on first run and changed the plan.** The reserve as "
      "originally written asked for 12% Indic and 10% long-context. Both "
      "exceeded what their own eligibility rules could supply at one epoch — a "
      "roughly 9.5B-token shortfall across the two, meaning the plan was "
      "promising a cooldown it could not stock. Indic dropped to "
      f"{spec.LANES['indic']['phases'][-1]:.0f}%, long-context to "
      f"{spec.LANES['longctx']['phases'][-1]:.0f}%, and the freed 3% went to "
      "code and web, which have eligible headroom. The Phase D column in §4 is "
      "the corrected one.")
    w("")
    if tight:
        names = ", ".join(f"**{x['label']}** ({T(x['eligible'])} eligible against "
                          f"{T(x['demand'])} demanded)" for x in tight)
        w(f"Still tight after the correction: {names}. These clear by under 15% "
          f"and should be treated as binding constraints on any future increase "
          f"to the reserve, not as slack.")
        w("")
    w("Note what the yields imply: only ~15% of The Stack v2 has a runnable test "
      "suite that goes green, so 'execution-verified code' is a far smaller pool "
      "than 'code'. A reserve that assumed otherwise would have been the "
      "highest-stakes wishful accounting in the document, because the anneal is "
      "where capability is actually decided.")
    w("")

    # -- schedule mechanics ---------------------------------------------------
    w("### 10.2 Learning-rate schedule")
    w("")
    lr = spec.LR_SCHEDULE
    w("Without this the anneal is undefined. A cooldown's effect comes from the "
      "learning rate decaying to zero *while* the premium data is in front of "
      "the model — an earlier draft specified only the data half and called it "
      "an anneal.")
    w("")
    w("| Segment | Shape | From → to |")
    w("|---|---|---|")
    w(f"| Warmup ({lr['warmup_frac']*100:.1f}% of tokens) | {lr['warmup_shape']} "
      f"| 0 → {lr['peak']:.1e} |")
    w(f"| Phases A–C | {lr['main_shape']} | {lr['peak']:.1e} → "
      f"{lr['peak']*lr['anneal_start_frac']:.1e} |")
    w(f"| Phase D (the anneal) | {lr['anneal_shape']} | "
      f"{lr['peak']*lr['anneal_start_frac']:.1e} → {lr['min_lr']:.0f} |")
    w("")
    w(f"- **Why not decay to zero before D:** {lr['main_note']}")
    w(f"- **Why linear in D:** {lr['anneal_note']}")
    w(f"- **Re-warming:** {lr['rewarm']}")
    w("")
    w(f"{lr['why_this_shape']}")
    w("")
    w("Warmup is a **fraction**, not an absolute token count. Specifying it as "
      "15B absolute — 0.5% of this run — would have made it 75% of a 20B proxy "
      "arm, and every arm would have been compared while still warming up. The "
      "proxy harness dry-run caught this.")
    w("")
    w("### 10.3 Sequence-length ladder")
    w("")
    w("Session 5 gave three hard constraints that an earlier draft waved at. "
      "**Every example in a batch has the same length** — mixed-length batches "
      "are not possible. **Nothing below "
      f"{spec.SEQ_MIN:,} tokens**, because padding short samples burns compute "
      "for nothing. **Length doubles up the ladder**; V4 ran 4K→8K→16K→32K→64K.")
    w("")
    w("| Phase | Sequence length | Examples/batch | Tokens/batch | Share of phase | Note |")
    w("|---|---|---|---|---|---|")
    for s in r["seq_ladder"]:
        w(f"| {s['phase']} | {s['seq_len']:,} | {s['batch_examples']} | "
          f"{s['tokens_per_batch']:,} | {s['share_of_phase']}% | {s['note']} |")
    w("")
    w("**Tokens-per-batch is held constant** at "
      f"{r['seq_ladder'][0]['tokens_per_batch']:,} by halving the example count "
      "at each doubling — asserted by the build. Otherwise every length change "
      "is also a batch-size change, and a loss spike could not be attributed to "
      "either. Long context is a batch-construction decision as much as a data "
      "decision, which is why it lives in the curriculum spec rather than in an "
      "implementation note.")
    w("")
    w("### 10.4 Band transitions")
    w("")
    bt = spec.BAND_TRANSITION
    w(f"**{bt['why']}** An earlier draft stepped hard at every phase edge — "
      f"precisely the failure mode described.")
    w("")
    w(f"- **Crossfade:** {bt['overlap_note']}")
    w(f"- **Gradient-norm target:** {bt['grad_norm_target']}, trip at "
      f"{bt['grad_norm_trip']}.")
    w(f"- **On trip:** {bt['trip_action']}")
    w(f"- **Monitored:** {', '.join(bt['monitored'])}.")
    w("")
    w("Arm A6 (§13.2) removes the crossfade and measures loss-spike count and "
      "peak gradient norm rather than end-task accuracy, so the complexity is "
      "ablated rather than assumed. Compare "
      "`python run_proxy.py --dry-run --arm A0 --stage train` against `--arm A6` "
      "at frac 0.38 to see the interpolation.")
    w("")

    # -- bands ---------------------------------------------------------------
    w("## 11. Difficulty and reasoning-length bands")
    w("")
    w("### 11.1 Difficulty bands")
    w("")
    ph = " | ".join(p["id"] for p in phases)
    w(f"| Band | {ph} | Concrete example | Why this band |")
    w("|---|" + "---|" * len(phases) + "---|---|")
    for b in r["difficulty_bands"]:
        mix = " | ".join(f"{v}" for v in b["phase_mix"])
        w(f"| **{b['id']} {b['label']}** | {mix} | *{b['example_source']}:* "
          f"{b['example']} | {b['why']} |")
    w("")
    w("Columns are the share of that phase's samples, and each sums to 100. "
      "D1 never drops to zero: the foundational band is what keeps syntax and "
      "tokenizer priors sharp, and removing it entirely is a known way to "
      "destabilise late training.")
    w("")
    w("### 11.2 Reasoning-length bands")
    w("")
    w("The band is supplied **in the prompt as a control token**, and the model "
      "is trained to answer within it. Session 5 asked why the model cannot "
      "choose its own depth: because if depth is rewarded only through final "
      "correctness, maximum depth always wins — you have paid an employee by the "
      "hour and asked them to decide the hours. Depth is an input.")
    w("")
    w("| Band | Control token | Budget | Share of reasoning lane | Worked example | Answer |")
    w("|---|---|---|---|---|---|")
    for b in r["length_bands"]:
        lo, hi = b["token_budget"]
        w(f"| **{b['id']}** | `{b['control']}` | {lo}–{hi:,} tok | "
          f"{b['share_of_reasoning_lane']}% | **Q:** {b['example_q']}<br>"
          f"**Trace:** {b['example_trace']} | {b['example_a']} |")
    w("")
    be = spec.BAND_ENFORCEMENT
    w(f"Enforcement: `{be['overlength_policy']}` with a {be['tolerance_pct']}% "
      f"tolerance. A trace that overruns its band is truncated at the ceiling and "
      f"the sample is **dropped**, not trained past the boundary — otherwise the "
      f"band is a suggestion and the model learns the ceiling is negotiable. The "
      f"`high` example's answer (597) is computed at build time by "
      f"`audit.count_4digit_digitsum`, not asserted.")
    w("")

    # -- masking -------------------------------------------------------------
    w("## 12. Loss-masking policy")
    w("")
    w("| Segment | Policy | Why |")
    w("|---|---|---|")
    for m in spec.MASKING:
        w(f"| {m['segment']} | `{m['policy']}` | {m['why']} |")
    w("")
    w("This is why the agentic lane's budget share and its capability share "
      "differ by more than 3×, and why §4 reports both.")
    w("")

    # -- proxy ---------------------------------------------------------------
    w("## 13. The proxy experiment")
    w("")
    p1, p3 = spec.PROXY["scale_1b"], spec.PROXY["scale_3b"]
    c = spec.PROXY["cluster"]
    w(f"**{len(spec.PROXY['arms'])} arms at {T(p1['params'])} params × "
      f"{T(p1['tokens_per_arm'])} tokens, then a {T(p3['params'])} × "
      f"{T(p3['tokens_per_arm'])} confirmation of the baseline and the winner.** "
      f"{c['gpus']}× {c['device']} at {c['mfu']*100:.0f}% MFU, "
      f"{usd(c['usd_per_gpu_hour'])}/GPU-h.")
    w("")
    w(f"| | Per arm | Arms | GPU-hours | Cost |")
    w("|---|---|---|---|---|")
    w(f"| 1B screen | {cost['arm_1b']['hours']:.1f} h | {cost['n_1b']} | "
      f"{cost['arm_1b']['gpu_hours']*cost['n_1b']:,.0f} | "
      f"{usd(cost['arm_1b']['usd']*cost['n_1b'])} |")
    w(f"| 3B confirm | {cost['arm_3b']['hours']:.1f} h | {cost['n_3b']} | "
      f"{cost['arm_3b']['gpu_hours']*cost['n_3b']:,.0f} | "
      f"{usd(cost['arm_3b']['usd']*cost['n_3b'])} |")
    w(f"| **Total** | | | | **{usd(cost['total_usd'])}** |")
    w(f"| Full 40B run | {cost['full_run']['days']:.1f} days | 1 | "
      f"{cost['full_run']['gpu_hours']:,.0f} | {usd(cost['full_run']['usd'])} |")
    w("")
    w(f"The screen costs **{cost['pct_of_full']:.3f}%** of the run it is "
      f"protecting.")
    w("")
    w("### 13.1 The corpus is scaled, not just the model")
    w("")
    pp = r["proxy_pools"]
    w(f"An earlier draft ran 1B params on 20B tokens and left the candidate "
      f"pools at full size. At that budget the code lane would have drawn "
      f"{T(pp['rows'][1]['demand'])} against ~{T(by_id['code']['supply_usable'])} "
      f"of supply: **0.006 epochs**. Arm A3 exists to falsify the repetition "
      f"ceiling and would never have repeated a single token — it would have "
      f"silently degenerated into 'more code, less web at constant freshness' "
      f"while appearing to test a data-constrained regime.")
    w("")
    w(f"Every lane's pool is therefore subsampled by the same factor as the "
      f"budget (**×{pp['factor']:.3e}**), so proxy epochs equal full-run epochs "
      f"lane by lane. The build asserts this equality rather than trusting it.")
    w("")
    w("| Lane | Proxy pool | Proxy demand | Proxy epochs | Full-run epochs |")
    w("|---|---|---|---|---|")
    for x in pp["rows"]:
        ep = "∞" if x["epochs"] == float("inf") else f"{x['epochs']:.2f}"
        fe = "∞" if x["full_epochs"] == float("inf") else f"{x['full_epochs']:.2f}"
        w(f"| {x['label']} | {T(x['pool'])} | {T(x['demand'])} | **{ep}** | {fe} |")
    w("")
    w(f"**What this still does not fix, stated rather than buried.** The proxy "
      f"runs at **{pp['tokens_per_param_proxy']:.0f} tokens/param** against the "
      f"full run's **{pp['tokens_per_param_full']:.0f}** — Chinchilla-optimal "
      f"versus heavily over-trained. Corpus scaling makes the *data-constrained* "
      f"regime match; it does not make the *over-trained* regime match, and the "
      f"3B confirmation does not close that gap either. Mixture conclusions that "
      f"depend on being far past Chinchilla-optimal are not tested by this "
      f"screen. The honest scope of the experiment is **relative mixture ranking "
      f"under matched repetition pressure** — which is what the decision rules "
      f"in §13.4 are written against, and nothing wider.")
    w("")
    w("### 13.2 Arms")
    w("")
    w("| Arm | Change from baseline | What it tests |")
    w("|---|---|---|")
    for a in spec.PROXY["arms"]:
        w(f"| **{a['id']} {a['name']}** | {a['change']} | {a['tests']} |")
    w("")
    w("### 13.3 Metrics")
    w("")
    w("| Lane | Metric | Note |")
    w("|---|---|---|")
    for m in spec.PROXY["metrics"]:
        w(f"| `{m['lane']}` | {m['metric']} | {m['floor_note'] or '—'} |")
    w("")
    w("Indic results are reported per language and **never averaged** — an "
      "average across 22 languages hides exactly the collapse the floor exists "
      "to prevent.")
    w("")
    w("### 13.4 Pre-registered decision rules")
    w("")
    w("Written before the runs, so a result cannot be reinterpreted after the "
      "fact. Each rule names the number that would refute the corresponding "
      "choice in this document.")
    w("")
    w("| Keep | If and only if | Otherwise |")
    w("|---|---|---|")
    for d in spec.PROXY["decisions"]:
        w(f"| {d['rule']} | {d['iff']} | {d['else_']} |")
    w("")
    w("**A4 is the arm that can invalidate this entire document.** If the static "
      "mixture matches the four-phase curriculum on every metric, then phasing, "
      "the anneal reserve and the difficulty schedule are all elaborate "
      "no-ops and only the totals in §4 matter. That outcome is stated here as "
      "an acceptable result, not a failure to be explained away.")
    w("")

    # -- decontamination + sensitivity ---------------------------------------
    w("### 13.5 Decontamination")
    w("")
    dc = spec.DECONTAMINATION
    w(f"- **Method:** {dc['method']}")
    w(f"- **When:** {dc['when']}")
    w(f"- **Action:** {dc['action']}")
    w(f"- **Reported:** {dc['report']}")
    w("")
    w(f"Suites specified ({len(dc['suites'])}): {', '.join(dc['suites'])}.")
    w("")
    dm = r.get("decon")
    if not dm:
        w(f"> **Status: NOT YET MEASURED.** {dc['measured_note']}")
        w("")
    else:
        w("**Measured.** `decon/measure.py` fetches real test items through the "
          "HF datasets-server and scans the corpora we actually hold. Pure "
          "standard library — no tokenizer, so n-grams are over whitespace "
          "tokens and are comparable across scripts.")
        w("")
        w("| Corpus | Docs | Words | 12-gram hits | Rate | Detection floor |")
        w("|---|---|---|---|---|---|")
        for c in dm["corpora"]:
            hits = c["hits_12gram"]
            hs = ", ".join(f"{k}: {v}" for k, v in hits.items()) or "none"
            w(f"| {c['name']} | {c['docs']:,} | {c['words']:,} | {hs} | "
              f"**{c['rate_pct']:.4f}%** | {c['detection_floor_pct']:.4f}% |")
        w("")
        idx_total = sum(s["distinct_12grams"] for s in dm["index_stats"])
        w(f"Index: **{idx_total:,} distinct 12-grams** across "
          f"{len(dm['index_stats'])} suites "
          f"({', '.join(s['suite'] for s in dm['index_stats'])}).")
        w("")
        w("**What the two hits actually are.** Both are the same fragment — "
          "`while left <= right: mid = (left + right) // 2 if` — matching MBPP. "
          "That is a textbook binary search, not evidence of shared provenance. "
          "The plan's stated policy (strip the whole document) would remove them "
          "anyway, which is the right default, but calling this *contamination* "
          "would overstate what was found.")
        w("")
        w("[[NOTE]] **The Telugu zero is reported as a bound, not a result**, per this "
          "section's own rule that an exact zero is a detector failure to "
          "investigate. The detector demonstrably works — it fires on the code "
          f"corpus — so the honest statement is that contamination is below "
          f"~{dm['corpora'][0]['detection_floor_pct']:.3f}% on an 11.6k-document "
          "sample, not that it is absent. Two further caveats: FLORES-200 is "
          "gated behind authentication, so **Belebele** (whose passages are "
          "drawn from FLORES) stands in for it; and MMLU and ARC contribute few "
          "12-grams because many of their items are shorter than twelve words "
          "(139 and 83 items respectively are unindexable at n=12, and fall "
          "back to a 6-gram pass).")
        w("")
        w("### 13.6 The first run of this measurement was wrong")
        w("")
        w("Worth recording, because it is the failure mode this whole document "
          "is about. The first scan reported **0.560%** contamination on Telugu "
          "and **0.105%** on the reasoning corpus. Both were artefacts of the "
          "normaliser:")
        w("")
        w("- The tokeniser stripped punctuation with `[^\\w\\s]`. Python's `\\w` "
          "does not match Unicode combining marks (categories Mn/Mc), so Telugu "
          "vowel signs and viramas were treated as punctuation and replaced with "
          "spaces — **shattering every Telugu word into individual consonants**. "
          "A 12-gram of twelve bare consonants collides by chance. This is the "
          "same class of bug the session-4 pipeline guarded against with Brahmic "
          "joiner preservation, reintroduced by a one-line regex.")
        w("- On code, the same stripping turned `for i in range(i+1, n):` into "
          "`for i in range i 1 n`, discarding precisely the structure that makes "
          "a fragment distinctive. The matches were generic nested-loop idioms.")
        w("")
        w("Keeping punctuation dropped the measured rates to 0.0000% and "
          "0.0209%. A number produced by a broken detector looks exactly like a "
          "number produced by a working one, which is why the examples are "
          "printed and inspected rather than just the rate.")
        w("")

    # -- micro-proxy ---------------------------------------------------------
    mp = r.get("microproxy")
    if mp:
        w("### 13.7 The micro-proxy: what was actually run")
        w("")
        a0 = mp["arms"].get("A0", {})
        w(f"The screen in §13.1–13.4 has **not** been run — it needs GPUs we do "
          f"not have. What *was* run is a deliberately narrower experiment on "
          f"the hardware available (one RTX 3070 Laptop, 8GB), targeting only "
          f"the two claims in this plan that are **training-dynamics** claims "
          f"rather than capability claims. Those are the only ones an "
          f"{a0.get('runs',[{}])[0].get('params',0)/1e6:.1f}M-parameter model "
          f"can speak to.")
        w("")
        w(f"- **A0 vs A6** — does the 15% band crossfade (§10.4) actually "
          f"suppress instability at a mixture transition?")
        w(f"- **A0 vs A2** — does an always-on floor (§9) retain a minority lane "
          f"better than introducing it late **at matched total share**?")
        w("")
        w("Setup: byte-level vocab (256), two lanes drawn from the corpora we "
          "actually hold — Telugu web and the English reasoning/SFT mix — with "
          "the disjoint held-out slices session 4 froze. Byte-level is "
          "deliberate: cl100k's fertility differs 5.78× between these two lanes "
          "(§5.1), so a subword tokenizer would make *share of tokens* mean "
          "something different per lane, which is the exact error §5.1 exists to "
          "prevent.")
        w("")
        w("| Arm | Indic share by phase | Crossfade | Purpose |")
        w("|---|---|---|---|")
        for aid in ("A0", "A2", "A6"):
            a = mp["arms"].get(aid)
            if not a:
                continue
            run0 = a["runs"][0]
            w(f"| **{aid}** | {'/'.join(str(int(x)) for x in run0['indic_schedule'])} | "
              f"{run0['crossfade']*100:.0f}% | {a['name']} |")
        w("")
        w("A2's schedule is chosen so its **total** indic share matches A0's "
          "(33.3% vs 33.0%). The arms differ in *ordering*, not budget — "
          "otherwise it would be measuring the obvious.")
        w("")
        w("| Arm | Seeds | Spike rate in transition | Spike rate outside | Peak grad-norm in transition | Final bpb indic | Final bpb reasoning |")
        w("|---|---|---|---|---|---|---|")
        for aid in ("A0", "A2", "A6"):
            a = mp["arms"].get(aid)
            if not a:
                continue
            w(f"| **{aid}** | {a['n_seeds']} | {a['spike_rate_in_transition']:.4f} | "
              f"{a['spike_rate_outside']:.4f} | {a['peak_gnorm_transition']:.3f} | "
              f"{a['final_bpb_indic']:.4f} | {a['final_bpb_reasoning']:.4f} |")
        w("")
        cc = mp.get("claim_crossfade")
        if cc:
            w(f"**Crossfade (A0 vs A6).** Pre-registered rule: *{cc['rule']}*")
            w("")
            sr = cc.get("spike_ratio")
            w(f"Measured: A6's spike rate in transition windows is "
              f"{cc['a6_spike_rate_transition']:.4f} against A0's "
              f"{cc['a0_spike_rate_transition']:.4f}"
              + (f" — a ratio of **{sr:.2f}×**" if sr else "") +
              f". Peak gradient norm during transitions: A6 "
              f"{cc['a6_peak_gnorm_transition']:.3f} vs A0 "
              f"{cc['a0_peak_gnorm_transition']:.3f}.")
            w("")
            w(f"> **Verdict: {cc['verdict']}**")
            w("")
        cf = mp.get("claim_floor")
        if cf:
            w(f"**Floor (A0 vs A2).** Pre-registered rule: *{cf['rule']}*")
            w("")
            w(f"Measured: final held-out indic bits-per-byte is "
              f"{cf['a2_final_bpb_indic']:.4f} without the floor against "
              f"{cf['a0_final_bpb_indic']:.4f} with it — a delta of "
              f"**{cf['delta_bpb']:+.4f} bpb** at matched total share. Reasoning "
              f"lane: {cf['a2_final_bpb_reasoning']:.4f} vs "
              f"{cf['a0_final_bpb_reasoning']:.4f}.")
            w("")
            w(f"> **Verdict: {cf['verdict']}**")
            w("")
        w("#### Both pre-registered rules turned out to be untestable at this scale")
        w("")
        w("This is the most useful thing the run produced, and it is a finding "
          "about the *plan*, not about the mixture.")
        w("")
        if cc:
            w(f"**The spike-count rule had no power.** Across both arms and both "
              f"seeds the experiment recorded "
              f"**{cc.get('total_transition_spikes_A0_A6','?')} spike events "
              f"in total**. The 1.67× ratio above is a ratio of small integers — "
              f"it cannot distinguish a real effect from a coin flip. The "
              f"verdict therefore uses a *post-hoc* continuous metric "
              f"(per-step excess loss in robust-sigma units, defined at every "
              f"step rather than only at threshold crossings), which is stated "
              f"as post-hoc rather than presented as the plan. A reviewer who "
              f"rejects that substitution should read the pre-registered number "
              f"as INCONCLUSIVE, not as DROP.")
            w("")
            if cc.get("absolute_limb_note"):
                w(f"**The gradient-norm limb did not transfer at all.** "
                  f"{cc['absolute_limb_note']} A threshold written against the "
                  f"full run's 0.2 target fires unconditionally on an 11M model, "
                  f"so applying it here would have manufactured a KEEP verdict "
                  f"out of nothing.")
                w("")
        if cf and cf.get("noise_note"):
            w(f"**The bpb rule was swamped by seed noise.** {cf['noise_note']} "
              f"Running the *same arm* under a different seed moves indic bpb by "
              f"more than the between-arm effect does. Both seeds do agree on "
              f"the sign — A2 finished ahead on indic in both — but 2-of-2 sign "
              f"agreement is p=0.5 under a random-sign null, which is "
              f"suggestive and nothing more.")
            w("")
        w("The rules were not badly written; they were calibrated for 1B "
          "parameters on 20B tokens and neither survives the drop to 11M. **A "
          "plan that specifies decision rules without specifying the statistical "
          "power to resolve them has specified less than it appears to.** §13.4 "
          "should carry a required-events or minimum-detectable-effect column "
          "before those rules are trusted at 1B either — the same failure could "
          "recur there at a cost of $6,320 rather than an afternoon.")
        w("")
        w("**What this does not establish.** The model is "
          f"{a0.get('runs',[{}])[0].get('params',0)/1e6:.1f}M parameters trained "
          f"on {a0.get('runs',[{}])[0].get('tokens',0)/1e6:.0f}M byte-tokens — "
          "roughly 2 tokens per parameter, far below Chinchilla and further "
          "below the plan's 75. It says nothing about HumanEval, MMLU, GSM8K, "
          "BFCL, or any capability metric, and nothing about the seven lanes "
          "with no corpus. Two lanes is also the *easiest* possible transition "
          "test: a Telugu→English shift is far sharper than any boundary in the "
          "real schedule, so a crossfade effect that fails to appear here could "
          "still appear with nine lanes and gentler, more frequent transitions. "
          "The result bounds a claim; it does not settle it.")
        w("")

    w("## 14. Sensitivity")
    w("")
    w("Which assumptions, if wrong, change a conclusion. Each parameter is "
      "swung to its plausible bounds and **the entire plan is re-audited at "
      "each** — this is a computation, not a paragraph of reassurance.")
    w("")
    w("| Assumption | Low | Base | High | Conclusion |")
    w("|---|---|---|---|---|")
    for s in r["sensitivity"]:
        cells = []
        for b in ("low", "base", "high"):
            x = s["results"][b]
            if x.get("feasible"):
                cells.append(f"{x['epochs']:.2f} ep, {x['manufactured_pct']:.0f}% mfd, `{x['verdict']}`")
            else:
                cells.append("**INFEASIBLE**")
        verdict = "⚠️ **swings**" if s["swings_conclusion"] else "✅ holds"
        w(f"| {s['label']} | {cells[0]} | {cells[1]} | {cells[2]} | {verdict} |")
    w("")
    for s in r["sensitivity"]:
        w(f"- **{s['label']}** ({s['low']:g} / {s['base']:g} / {s['high']:g}) — "
          f"{s['basis']} *{s['breaks']}*")
    w("")
    swingers = [s for s in r["sensitivity"] if s["swings_conclusion"]]
    if swingers:
        w(f"**{len(swingers)} of {len(r['sensitivity'])} assumptions swing a "
          f"conclusion.** The Sangraha tokenizer is the severe one: at our own "
          f"measured cl100k fertility the plan becomes *infeasible* — the anneal "
          f"cannot be stocked, because the verified tier collapses to a fraction "
          f"of its assumed size. Four sources were checked for the tokenizer "
          f"AI4Bharat used (the HF dataset card, the arXiv abstract, the full "
          f"paper PDF, and the IndicLLMSuite GitHub README) and **none state "
          f"it**. Until it is resolved, the Indic conclusion in §7 should be "
          f"read as conditional.")
        w("")
        w("The two that hold are worth as much as the two that swing: the web "
          "dedup haircut can be as bad as 0.40 without the lane needing "
          "repetition at this budget, and the agentic lane stays "
          "overwhelmingly manufactured across a 9× swing in assumed trajectory "
          "length — so that conclusion is robust even though the number behind "
          "it is a guess.")
        w("")

    # -- attacks -------------------------------------------------------------
    w("## 15. Where this plan is weakest")
    w("")
    w(f"1. **The agentic lane is {ag['manufactured_pct']:.0f}% data that does not "
      f"exist yet.** Priced at {usd(ag_m['usd'])} and {ag_m['env_days']:.2f} days "
      f"of wall-clock (§6), but entirely contingent on a rollout harness V4 never "
      f"built. If the harness slips, the fallback in §6 fires and the lane drops "
      f"to its {spec.FLOOR['agentic']['pct']}% floor.")
    w(f"2. **Reasoning is {by_id['reasoning']['manufactured_pct']:.0f}% "
      f"synthetic.** Defensible by precedent (phi-4, Cosmopedia) and gated on "
      f"answer-checking, but it is the largest block of generated tokens in the "
      f"plan and it is generated by a model whose own reasoning we are trying to "
      f"build.")
    w("3. **Six inventory figures are `DERIVED` from an assumed mean "
      "tokens-per-sample, and three are `ESTIMATED`.** Every one is tagged in "
      "§8 and in `spec.py`. The agentic lane's verdict rests on a 30,000 "
      "tokens/trajectory assumption for Nemotron-SWE; if the true mean were 3× "
      "larger the lane would still be ~83% manufactured, so the conclusion is "
      "robust to that assumption even though the number is not.")
    w(f"4. **Sangraha's tokenizer is unstated, and §14 shows it is the one "
      f"assumption that can break the plan.** Four sources checked, none state "
      f"it. At our own measured cl100k fertility "
      f"({spec.TOKENIZER_FERTILITY['cl100k']['indic']:.3f} tok/word on Telugu "
      f"versus {spec.TOKENIZER_FERTILITY['muril']['indic']:.3f} under MuRIL) the "
      f"whole document becomes infeasible. Cheapest open item in the plan; "
      f"until it is closed, §7 is conditional.")
    w(f"5. **The 7.0% floor is asserted from a mechanism, not measured.** The "
      f"selector pathology is real and documented; the specific value is not. "
      f"Arm A2 is designed to kill it, and A2 only tests on/off — not the level.")
    w(f"6. **The selector's own value is unmeasured.** It costs 2× corpus (§5.2) "
      f"plus per-refresh compute, justified by a claimed 8× efficiency we have "
      f"not reproduced. Arm A5 now tests it; before this revision nothing did.")
    w(f"7. **The proxy remains at "
      f"{r['proxy_pools']['tokens_per_param_proxy']:.0f} tokens/param against "
      f"the run's {r['proxy_pools']['tokens_per_param_full']:.0f}.** Corpus "
      f"scaling matches the data-constrained regime, not the over-trained one. "
      f"Narrower than it was at 14T, but not closed.")
    w(f"8. **The decontamination measurement covers {dc.get('measured_scope','')}** "
      f"It is real within that scope and claims nothing outside it — but a "
      f"0.02% rate on two corpora is not evidence about the seven lanes that "
      f"have no corpus yet, and the suites that matter most for our targets "
      f"(the SWE-bench family, Terminal-Bench, τ-bench) are exactly the ones "
      f"not scannable this way.")
    w("")

    # -- cleaning ------------------------------------------------------------
    w("## 16. Where the cleaning goes next")
    w("")
    w("Priority here is **declared, not derived from manufactured share**. An "
      "earlier draft ranked purely by manufactured percentage, which at this "
      "budget dropped Indic off the table entirely — because Indic is 0% "
      "manufactured at 3T — while §2 was simultaneously arguing that the "
      "cleaning must switch to the Verified tier. The document told the reader "
      "to do something and then omitted it from the table saying what to do. "
      "**Starved is not the same as needs-manufacturing:** a lane can be well "
      "supplied in aggregate and still be cleaning the wrong tier of it.")
    w("")
    w("| Priority | Lane | Verdict | Manufactured | Why it ranks here | What to do |")
    w("|---|---|---|---|---|---|")
    for cp in sorted(spec.CLEANING_PRIORITY, key=lambda c: c["rank"]):
        a = by_id.get(cp["lane"])
        if not a:
            continue
        w(f"| **{cp['rank']}** | {a['label']} | `{a['verdict']}` | "
          f"{a['manufactured_pct']:.0f}% | {cp['why_now']} | {cp['action']} |")
    w("")
    w("Note that priority 1 carries a `REPEAT` verdict and 0% manufactured — it "
      "ranks first precisely because the constraint is *which tier*, not *how "
      "much*. Ranking by scarcity alone would have buried it.")
    w("")
    for f in getattr(spec, "CLEANING_FINDINGS", []):
        w(f"### 16.1 {f['title']}")
        w("")
        w(f"{f['finding']}")
        w("")
        m = f["measured"]
        w("| | Unverified (session 4) | Verified (this run) |")
        w("|---|---|---|")
        w(f"| Median stopword hits, first 250 words | {m['unverified_median_hits']} | **{m['verified_median_hits']}** |")
        w(f"| Mean document length (words) | {m['unverified_mean_words']} | **{m['verified_mean_words']}** |")
        w(f"| Share of documents below the threshold | {m['unverified_pct_below']}% | **{m['verified_pct_below']}%** |")
        w("")
        w(f"Rule: `{m['threshold']}`, against a {m['stopword_list_size']}-word "
          f"Telugu stopword list. Predicted rejection "
          f"{m['verified_pct_below']}% vs observed "
          f"{m['verified_observed_reject_pct']}% — the scan explains the funnel.")
        w("")
        w(f"**What this does not establish.** {f['not_established']}")
        w("")
        w(f"**Action.** {f['action']}")
        w("")

    # -- provenance ----------------------------------------------------------
    w("## 17. Provenance of every supply figure")
    w("")
    w("| Tag | Meaning | Count |")
    w("|---|---|---|")
    counts = {}
    for it in spec.INVENTORY:
        counts[it["provenance"]] = counts.get(it["provenance"], 0) + 1
    meanings = {
        "MEASURED": "produced by our own session-4 cleaning pipeline",
        "PUBLISHED": "stated on a dataset card or in a paper, cited by URL",
        "DERIVED": "published sample count × a stated mean-tokens-per-sample assumption",
        "ESTIMATED": "our own estimate, flagged, never load-bearing alone",
    }
    for k in ("MEASURED", "PUBLISHED", "DERIVED", "ESTIMATED"):
        if k in counts:
            w(f"| `{k}` | {meanings[k]} | {counts[k]} |")
    w("")
    w("Reproduce: `cd plan && python build_plan.py`")
    w("")

    md = "\n".join(L) + "\n"
    # Presentation pass: numeric column alignment, a linked contents block, and
    # the alert callouts marked above. Changes how the numbers read, never what
    # they are - it runs after every figure is already fixed.
    md = polish.apply(md, toc_after="[`plan/build_site.py`](plan/build_site.py).")
    with io.open(OUT_MD, "w", encoding="utf-8") as f:
        f.write(md)

    payload = json.loads(json.dumps(r, default=str))
    with io.open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, ensure_ascii=False)

    return md, r


if __name__ == "__main__":
    md, r = build()
    print(f"wrote {os.path.normpath(OUT_MD)}  ({len(md):,} chars, "
          f"{len(md.splitlines()):,} lines)")
    print(f"wrote {os.path.normpath(OUT_JSON)}")
    print(f"invariants OK | floor {r['floor_total']:.2f}% | "
          f"anneal {r['anneal']['pct_of_budget']:.1f}% | "
          f"manufacturing ${r['manufacturing_usd']:,.0f} | "
          f"proxy ${r['cost']['total_usd']:,.0f}")
